import {getGrowMealCategory} from "@/lib/competition/growmeal";
import {NextResponse} from "next/server";import {createClient} from "@/lib/supabase/server";import {createAdminClient} from "@/lib/supabase/admin";
export const dynamic="force-dynamic";
const classesByLevel:Record<string,Set<string>>={Nursery:new Set(["Nursery 1","Nursery 2","Nursery 3"]),Primary:new Set(["Primary 1","Primary 2","Primary 3","Primary 4","Primary 5","Primary 6"]),JSS:new Set(["JSS 1","JSS 2","JSS 3"]),SSS:new Set(["SSS 1","SSS 2","SSS 3"])};
const quests=new Set(["growmeal","growenergy","growaqua"]);
export async function POST(req:Request){try{const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:"AUTH_REQUIRED",message:"Please sign in again."},{status:401});
const body=await req.json();const name=String(body.displayName||"").trim(),level=String(body.schoolLevel||"").trim(),classLevel=String(body.classLevel||"").trim(),age=String(body.ageCategory||"").trim(),eligible=Array.isArray(body.questEligibility)?body.questEligibility.filter((q:any)=>quests.has(q)):[];
if(name.length<2||!classesByLevel[level]?.has(classLevel))return NextResponse.json({error:"INVALID_INPUT",message:"Select a valid school level and class/grade combination."},{status:400});
if(eligible.includes("growmeal")&&!getGrowMealCategory(level,classLevel))return NextResponse.json({error:"INVALID_INPUT",message:"This class is not mapped to a valid GrowMeal competition category."},{status:400});
const {data:mine}=await s.from("fewq_school_memberships").select("school_id,role,fewq_schools(status)").eq("user_id",user.id).eq("active",true);const admins=(mine||[]).filter((x:any)=>x.role==="school_admin"&&x.fewq_schools?.status==="active") as any[];if(admins.length!==1)return NextResponse.json({error:"ACCESS_DENIED",message:"An active school-admin account is required."},{status:403});
const admin=createAdminClient(),schoolId=admins[0].school_id;let code="";for(let i=0;i<4;i++){code="FEWC-"+crypto.randomUUID().replaceAll("-","").slice(0,10).toUpperCase();const {data,error}=await admin.from("fewq_competitors").insert({competitor_code:code,school_id:schoolId,display_name:name,school_level:level,class_level:classLevel,age_category:age||null,quest_eligibility:eligible,active:true,authorization_status:"authorized",created_by:user.id}).select("id,competitor_code").single();if(!error){await admin.from("fewq_audit_events").insert({event_type:"COMPETITOR_CREATED",actor_user_id:user.id,actor_role:"school_admin",school_id:schoolId,entity_type:"competitor",entity_id:data.id,metadata:{school_level:level,class_level:classLevel,quest_eligibility:eligible,growmeal_category:eligible.includes("growmeal")?getGrowMealCategory(level,classLevel)?.code:null}});return NextResponse.json({ok:true,competitor:data},{status:201})}if(error.code!=="23505")return NextResponse.json({error:"SERVER_ERROR",message:"Could not create competitor. Please try again."},{status:500})}return NextResponse.json({error:"SERVER_ERROR",message:"Could not generate a competitor code. Please try again."},{status:500})}catch{return NextResponse.json({error:"SERVER_ERROR",message:"The competitor service could not complete the request."},{status:500})}}
