import {NextResponse} from "next/server";import {createClient} from "@/lib/supabase/server";import {createAdminClient} from "@/lib/supabase/admin";
const roles=["teacher","competitor_manager"] as const;const languages=["en","ha","yo","ig","fr","ar"] as const;
export async function POST(req:Request){const origin=new URL(req.url).origin;const body=await req.json().catch(()=>({}));const email=String(body.email||"").trim().toLowerCase();const fullName=String(body.fullName||"").trim();const phone=String(body.phone||"").trim();const role=String(body.role||"");const preferredLanguage=String(body.preferredLanguage||"en");const locale=String(body.locale||"en");if(!email||!fullName||!roles.includes(role as any)||!languages.includes(preferredLanguage as any))return NextResponse.json({error:"INVALID_INPUT"},{status:400});
const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:"AUTH_REQUIRED"},{status:401});const {data:memberships}=await s.from("fewq_school_memberships").select("school_id,role,fewq_schools(status)").eq("user_id",user.id).eq("active",true);const adminMembership=(memberships||[]).find((m:any)=>m.role==="school_admin"&&m.fewq_schools?.status==="active") as any;if(!adminMembership)return NextResponse.json({error:"ACCESS_DENIED"},{status:403});
const a=createAdminClient();const listed=await a.auth.admin.listUsers({page:1,perPage:1000});let target=listed.data.users.find(u=>u.email?.toLowerCase()===email)||null;let created=false;
if(!target){const made=await a.auth.admin.createUser({email,email_confirm:true,user_metadata:{full_name:fullName,phone,preferred_language:preferredLanguage}});if(made.error||!made.data.user)return NextResponse.json({error:"ACCOUNT_CREATE_FAILED",message:made.error?.message||"Could not create staff account."},{status:400});target=made.data.user;created=true;}
const {data:other}=await a.from("fewq_school_memberships").select("id,school_id").eq("user_id",target.id).eq("active",true).neq("school_id",adminMembership.school_id).limit(1);if(other?.length)return NextResponse.json({error:"MEMBER_ALREADY_ASSIGNED",message:"This account is already assigned to another school."},{status:409});
await a.from("fewq_profiles").upsert({id:target.id,full_name:fullName,preferred_language:preferredLanguage},{onConflict:"id"});
const {data:existing}=await a.from("fewq_school_memberships").select("id").eq("school_id",adminMembership.school_id).eq("user_id",target.id).limit(1).maybeSingle();let membershipId=existing?.id;let err:any;if(existing){({error:err}=await a.from("fewq_school_memberships").update({role,active:true,updated_at:new Date().toISOString()}).eq("id",existing.id));}else{const inserted=await a.from("fewq_school_memberships").insert({school_id:adminMembership.school_id,user_id:target.id,role,active:true,created_by:user.id}).select("id").single();err=inserted.error;membershipId=inserted.data?.id;}if(err)return NextResponse.json({error:"SERVER_ERROR",message:err.message},{status:500});
const link=await a.auth.admin.generateLink({type:"recovery",email,options:{redirectTo:origin+"/auth/callback?next=/"+locale+"/login"}});if(link.error)return NextResponse.json({error:"SETUP_LINK_FAILED",message:link.error.message},{status:500});
await a.from("fewq_audit_events").insert({event_type:created?"MEMBER_ADDED":"MEMBER_ROLE_CHANGED",actor_user_id:user.id,actor_role:"school_admin",school_id:adminMembership.school_id,entity_type:"school_membership",entity_id:membershipId,metadata:{email,role,preferred_language:preferredLanguage,phone_present:Boolean(phone)}});
return NextResponse.json({ok:true,email,role,setupRequired:true,setupLink:link.data.properties?.action_link||null});}