"use client";
import {useMemo,useState} from "react";
type Q={id:string;question_code:string;competition_category:string;class_level:string|null;garden_code:string|null;garden_domain:string|null;question_text:string;lifecycle_status:string;competition_approved:boolean;difficulty:string};
type Cat={code:string;name:string;classes:readonly string[];gardenCodes:readonly string[]};
const states=["draft","content_review","answer_verified","approved","published","retired"];
export function QuestionBankAdmin({initialQuestions,categories}:{initialQuestions:Q[];categories:readonly Cat[]}){
 const [qs,setQs]=useState(initialQuestions),[category,setCategory]=useState("GM-NUR"),[klass,setKlass]=useState(""),[garden,setGarden]=useState(""),[status,setStatus]=useState(""),[open,setOpen]=useState(false),[importing,setImporting]=useState(false),[importMessage,setImportMessage]=useState("");
 const cat=categories.find(c=>c.code===category)!;
 const shown=useMemo(()=>qs.filter(q=>q.competition_category===category&&(!klass||q.class_level===klass)&&(!garden||q.garden_code===garden)&&(!status||q.lifecycle_status===status)),[qs,category,klass,garden,status]);
 const counts=Object.fromEntries(states.map(s=>[s,qs.filter(q=>q.competition_category===category&&q.lifecycle_status===s).length]));
 async function refresh(){const r=await fetch("/api/admin/growmeal/questions");if(r.ok)setQs((await r.json()).questions)}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body=Object.fromEntries(f.entries());const r=await fetch("/api/admin/growmeal/questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok){setOpen(false);await refresh()}else alert((await r.json()).error||"Could not add question")}
 async function bulkImport(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setImportMessage("");const form=e.currentTarget;const fd=new FormData(form);const file=fd.get("file");if(!(file instanceof File)||!file.size){setImportMessage("Choose a CSV or Excel (.xlsx) file first.");return}setImporting(true);try{const r=await fetch("/api/admin/growmeal/questions/import",{method:"POST",body:fd});const data=await r.json();if(!r.ok){const details=Array.isArray(data.errors)?data.errors.slice(0,5).join(" • "):"";setImportMessage((data.error||"Import failed.")+(details?" "+details:""));return}setImportMessage(`${data.imported} questions imported as drafts.`);form.reset();await refresh()}catch{setImportMessage("Import failed before the server returned a response. Please try again.")}finally{setImporting(false)}}
 async function transition(id:string,next:string){const r=await fetch(`/api/admin/growmeal/questions/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({lifecycle_status:next})});if(r.ok)await refresh();else alert((await r.json()).error||"Could not update question")}
 return <div className="qb-admin"><div className="qb-toolbar"><select value={category} onChange={e=>{setCategory(e.target.value);setKlass("");setGarden("")}}>{categories.map(c=><option key={c.code} value={c.code}>{c.code} — {c.name}</option>)}</select><select value={klass} onChange={e=>setKlass(e.target.value)}><option value="">All classes</option>{cat.classes.map(x=><option key={x}>{x}</option>)}</select><select value={garden} onChange={e=>setGarden(e.target.value)}><option value="">All gardens/domains</option>{cat.gardenCodes.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{states.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><button className="btn primary" onClick={()=>setOpen(!open)}>Add Question</button><a className="btn" href="/api/admin/growmeal/questions/import-template">Download import template</a></div><form className="qb-import" onSubmit={bulkImport}><label><b>Bulk import CSV / Excel</b><input name="file" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={importing}/></label><button className="btn primary" disabled={importing}>{importing?"Importing…":"Import questions"}</button>{importMessage&&<p role="status">{importMessage}</p>}</form>
 <div className="metric-grid">{states.map(s=><div className="metric" key={s}><strong>{counts[s]}</strong><span>{s.replaceAll("_"," ")}</span></div>)}</div>
 {open&&<form className="form-card qb-form" onSubmit={add}><input type="hidden" name="competition_category" value={category}/><label>Class<select name="class_level" required defaultValue=""><option value="" disabled>Select class</option>{cat.classes.map(x=><option key={x}>{x}</option>)}</select></label><label>Garden / domain<select name="garden_code" required defaultValue=""><option value="" disabled>Select garden</option>{cat.gardenCodes.map(x=><option key={x}>{x}</option>)}</select></label><label>Domain name<input name="garden_domain" placeholder="Optional descriptive domain"/></label><label>Question<textarea name="question_text" required/></label>{["A","B","C","D"].map(x=><label key={x}>Option {x}<input name={`option_${x.toLowerCase()}`} required/></label>)}<label>Correct answer<select name="correct_option" required>{["A","B","C","D"].map(x=><option key={x}>{x}</option>)}</select></label><label>Explanation<textarea name="explanation"/></label><label>Difficulty<select name="difficulty"><option value="foundation">Foundation</option><option value="standard">Standard</option><option value="advanced">Advanced</option></select></label><button className="btn primary">Save Draft</button></form>}
 <div className="qb-table"><div className="qb-row qb-head"><b>Code</b><b>Category / class</b><b>Garden</b><b>Question</b><b>Status</b><b>Workflow</b></div>{shown.map(q=><div className="qb-row" key={q.id}><span>{q.question_code}</span><span>{q.competition_category}<br/>{q.class_level}</span><span>{q.garden_code}<br/>{q.garden_domain}</span><span>{q.question_text}</span><span className="status-pill">{q.lifecycle_status.replaceAll("_"," ")}</span><span className="qb-actions">{q.lifecycle_status==="draft"&&<button onClick={()=>transition(q.id,"content_review")}>Review</button>}{q.lifecycle_status==="content_review"&&<button onClick={()=>transition(q.id,"answer_verified")}>Verify answer</button>}{q.lifecycle_status==="answer_verified"&&<button onClick={()=>transition(q.id,"approved")}>Approve</button>}{q.lifecycle_status==="approved"&&<button onClick={()=>transition(q.id,"published")}>Publish</button>}{q.lifecycle_status!=="retired"&&<button onClick={()=>transition(q.id,"retired")}>Retire</button>}</span></div>)}{!shown.length&&<div className="empty-state">No questions match these filters. GM-NUR is ready to populate first.</div>}</div></div>
}